# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline. DO NOT EDIT.
class OcRig < Formula
  desc "OC Rig — community fork of the AI coding agent for the terminal."
  homepage "https://github.com/toshon-jennings/opencode-rig"
  version "0.1.197"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toshon-jennings/opencode-rig/releases/download/v0.1.197/opencode-darwin-x64.zip"
      sha256 "PLACEHOLDER_SHA256_MAC_X64"

      def install
        bin.install "opencode" => "oc-rig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toshon-jennings/opencode-rig/releases/download/v0.1.197/opencode-darwin-arm64.zip"
      sha256 "PLACEHOLDER_SHA256_MAC_ARM64"

      def install
        bin.install "opencode" => "oc-rig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/toshon-jennings/opencode-rig/releases/download/v0.1.197/opencode-linux-x64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_X64"
      def install
        bin.install "opencode" => "oc-rig"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/toshon-jennings/opencode-rig/releases/download/v0.1.197/opencode-linux-arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
      def install
        bin.install "opencode" => "oc-rig"
      end
    end
  end
end
